[tox]
min_version = 4.22
envlist = py39,py310,py311,py312,py313,py314


[testenv]
dependency_groups = dev
commands =
    pytest {posargs}
set_env =
    # Put coverage files in .tox/py3xx/
    COVERAGE_FILE = {env_dir}{/}.coverage
    COVERAGE_HTML_DIR = {env_dir}{/}htmlcov
